[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "multi_asset.sw"
license = "Apache-2.0"
name = "multi_src15_asset"

[dependencies]
src15 = { path = "../../../standards/src15" }
src20 = { path = "../../../standards/src20" }
src7 = { path = "../../../standards/src7" }
