[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "without_configurables.sw"
license = "Apache-2.0"
name = "without_configurables_src11_registry"

[dependencies]
src11 = { path = "../../../standards/src11-contract-factory" }
