[package]
name = "sway-standards"
version = "0.6.1"
edition = "2021"

[[test]]
harness = true
name = "sway-standards-examples-tests"
path = "examples/harness.rs"

[dependencies]
fuels = { version = "0.66.1" }
tokio = { version = "1.12", features = ["rt", "macros"] }