[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "multi_asset_vault"

[dependencies]
src6 = { path = "../../../standards/src6" }
src20 = { path = "../../../standards/src20" }
