[workspace]

[package]
name = "publisher"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
petgraph = "0.6"
serde = { version = "1.0", features = ["derive"] }
toml_edit = { version = "0.22" }
