[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
categories = ["Standards", "Authentication", "Metadata"]
description = "The SRC-17 Standard defines a naming verification standard for onchain identities using offchain data."
documentation = "https://docs.fuel.network/docs/sway-standards/src-17-naming-verification/"
entry = "src17.sw"
homepage = "https://github.com/FuelLabs/sway-standards"
keywords = ["standard", "library"]
license = "Apache-2.0"
name = "src17"
organization = "FuelLabs"
repository = "https://github.com/FuelLabs/sway-standards"
version = "0.8.2"

[dependencies]
ownership = "0.26.0"
