[package]
name = "src7_metadata"
version = "0.6.1"
edition = "2021"

[[test]]
harness = true
name = "src7_metadata_tests"
path = "tests/harness.rs"

[dependencies]
fuels = { version = "0.66.1" }
tokio = { version = "1.12", features = ["rt", "macros"] }