[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "uninitialized_example.sw"
license = "Apache-2.0"
name = "uninitialized_src5_example"

[dependencies]
standards = { path = "../../../standards" }
