[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "with_configurables.sw"
license = "Apache-2.0"
name = "with_configurables_src12_registry"

[dependencies]
standards = { path = "../../../standards" }
