[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "hardcoded-information"

[dependencies]
src11 = { path = "../../../standards/src11-security-information" }
