[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "src10.sw"
license = "Apache-2.0"
name = "src10"
version = "0.8.2"
description = "The SRC-10 Standard allows for the implementation of a standard API for Native Bridges using the Sway Language."
homepage = "https://github.com/FuelLabs/sway-standards"
repository = "https://github.com/FuelLabs/sway-standards"
documentation = "https://docs.fuel.network/docs/sway-standards/src-10-native-bridge/"
organization = "FuelLabs"
categories = ["Interoperability", "Standards", "Native Assets"]
keywords = ["standard", "library"]

[dependencies]
