[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "src20.sw"
license = "Apache-2.0"
name = "src20"
version = "0.8.2"
description = "The SRC-20 Standard allows for the implementation of a standard API for Native Assets using the Sway Language."
homepage = "https://github.com/FuelLabs/sway-standards"
repository = "https://github.com/FuelLabs/sway-standards"
documentation = "https://docs.fuel.network/docs/sway-standards/src-20-native-asset/"
organization = "FuelLabs"
categories = ["Standards", "Metadata"]
keywords = ["standard", "library"]

[dependencies]
