[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "owned.sw"
license = "Apache-2.0"
name = "owned_src14"

[dependencies]
src14 = { path = "../../../standards/src14" }
src5 = { path = "../../../standards/src5" }
