[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "standards.sw"
license = "Apache-2.0"
name = "standards"

[dependencies]
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.25.0" }
