[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "sparse_merkle_proof"

[dependencies]
src17 = { path = "../../../standards/src17" }
merkle = { git = "https://github.com/FuelLabs/sway-libs", branch = "master" }
