[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "src11.sw"
license = "Apache-2.0"
name = "src11"
version = "0.8.0"
description = "The SRC-11 Standard allows for contract creators to make communication information readily available to everyone, with the primary purpose of allowing white hat hackers to coordinate a bug-fix or securing of funds."
homepage = "https://github.com/FuelLabs/sway-standards"
repository = "https://github.com/FuelLabs/sway-standards"
documentation = "https://docs.fuel.network/docs/sway-standards/src-11-security-information/"
organization = "FuelLabs"
categories = ["Metadata", "Standards", "Security"]
keywords = ["standard", "library"]

[dependencies]
