name: Docs

on:
  pull_request:

jobs:
  test:
    uses: FuelLabs/github-actions/.github/workflows/mdbook-docs.yml@master
    with:
      docs-src-path: 'docs/src'
      spellcheck-config-path: 'docs/.spellcheck.yml'