name: Docs

on:
  pull_request:

jobs:
  spell-check:
    name: Spell Check
    uses: FuelLabs/github-actions/.github/workflows/mdbook-docs.yml@master
    with:
      docs-src-path: "docs/book/src"
      spellcheck-config-path: "docs/book/.spellcheck.yml"

  link-check:
    name: Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          configuration-path: "docs/book/.markdown-link-check.json"
