name: github pages

on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  RUST_VERSION: 1.77.0
  FORC_VERSION: 0.56.0
  CORE_VERSION: 0.24.2

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.15"

      - run: mdbook build ./docs/book

      - name: Deploy master
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book/book
          destination_dir: book
        if: github.ref == 'refs/heads/master'

  deploy-forc-doc-sway-standards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Init cache
        uses: Swatinem/rust-cache@v2

      - name: Install Fuel toolchain
        uses: FuelLabs/action-fuel-toolchain@v0.6.0
        with:
          name: my-toolchain
          components: forc@${{ env.FORC_VERSION }}, fuel-core@${{ env.CORE_VERSION }}

      - name: Build sway-standards docs
        run: |
          forc doc --manifest-path standards

      - name: Deploy master std
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./standards/out/doc
          destination_dir: master
        if: github.ref == 'refs/heads/master'

      - name: Get tag
        id: branch_name
        run: |
          echo ::set-output name=BRANCH_NAME::${GITHUB_REF#refs/tags/}
        if: startsWith(github.ref, 'refs/tags')

      - name: Deploy std tag
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./standards/out/doc
          destination_dir: ${{ steps.branch_name.outputs.BRANCH_NAME }}
        if: startsWith(github.ref, 'refs/tags')
