name: Standards Nightly Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC
  pull_request:

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io

jobs:
  standards-nightly-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - name: Init cache
        uses: Swatinem/rust-cache@v2

      - name: Install a modern linker (mold)
        uses: rui314/setup-mold@v1

      - name: Force Rust to use mold globally for compilation
        run: |
          touch ~/.cargo/config.toml
          echo "[target.x86_64-unknown-linux-gnu]" > ~/.cargo/config.toml
          echo 'linker = "clang"' >> ~/.cargo/config.toml
          echo 'rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]' >> ~/.cargo/config.toml

      - name: Install Fuel toolchain
        uses: FuelLabs/action-fuel-toolchain@v0.6.0
        with:
          toolchain: nightly

      - name: Check Sway Formatting Standards
        run: forc fmt --path standards --check

      - name: Build All Standards
        run: forc build --error-on-warnings --path standards

      - name: Check Sway Formatting Examples
        run: forc fmt --path examples --check

      - name: Build All Examples
        run: forc build --path examples --release
        
      - name: Run Cargo Tests
        run: cargo test